In [9]:
import pandas as pd

pd.options.display.max_columns = 999

In [54]:
def sample(df, n=3):
    display(df.sample(n))
    display(df.shape)

In [ ]:
df = pd.read_json("data/locations.jsonl", lines=True)
sample(df, 3)

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode,horaires,infos,metro,bus,tram,parking,debutInfos,finInfos,ville,id,phone,urlBlood,urlPlasma,urlPlatelets
426,None,None,PLESTIN LES GREVES,Salle des Fêtes,0,PLESTIN LES GREVES,1,0,0,16.0,F18011,48.663820,-3.611633,Salle des Fêtes,,1,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3186,None,None,None,PLEURTUITPL MOBILE,0,,1,0,0,16.0,F78049,0.000000,0.000000,PLEURTUITPL MOBILE,,1219,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,BATIMENT 2 SALLES S021 S022 et S023,2 Rue le Coat Saint-Haouen,LORIENT,FAC SCIENCES,0,BATIMENT 2 SALLES S021 S022 et S023 2 Rue le C...,1,0,0,16.0,F30283,47.747202,-3.393352,LORIENT-Fac Sciences 9 h 13 h,56100,3,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(3249, 30)

In [56]:
df.isna().sum(axis=0).sort_values(ascending=False)

ville                   3249
urlPlatelets            3249
id                      3249
urlPlasma               3249
urlBlood                3249
phone                   3249
debutInfos              3249
finInfos                3249
tram                    3249
parking                 3249
metro                   3249
bus                     3249
infos                   3249
horaires                3248
address1                2527
address2                 658
city                     311
convocationLabel         116
name                       5
regionCode                 1
distance                   0
fullAddress                0
longitude                  0
latitude                   0
groupCode                  0
givePlatelet               0
giveBlood                  0
givePlasma                 0
samplingLocationCode       0
postCode                   0
dtype: int64

In [57]:
na_cols = ["ville", "urlPlatelets", "urlPlasma", "urlBlood", "id", "phone", "debutInfos", "finInfos", "tram", "parking", "metro", "bus", "infos", "horaires"]

df.drop(columns=na_cols, inplace=True)
sample(df, 3)

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode
1870,None,Parking CENTRE LECLERC de PONT L'ABBE,PONT L'ABBE,LIONS CLUB CAMION EFS*,0,Parking CENTRE LECLERC de PONT L'ABBE 29120 PO...,1,0,0,16.0,F50133,47.864960,-4.227608,LIONS CLUB,29120,1062
282,None,None,None,TREVOU TREGUINEC,0,,1,0,0,16.0,F10164,0.000000,0.000000,TREVOU TREGUINEC,,1311
494,None,AVENUE PIERRE DUGOR,AURAY,GYMNASE DE LA FORET,0,AVENUE PIERRE DUGOR 56400 AURAY,1,0,0,16.0,F30105,47.673339,-2.983224,AURAY GYMNASE MATIN,56400,9

(3249, 16)

In [58]:
df.postCode.isnull().sum()

np.int64(0)

In [59]:
df.postCode.str.len().value_counts()

postCode
5    2665
0     584
Name: count, dtype: int64

In [60]:
df_no_postcode = df[df.postCode == ""]
sample(df_no_postcode, 3)

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode
1989,None,None,PLONEVEZ DU FAOU,SALLE MUNICIPALE,0,PLONEVEZ DU FAOU,1,0,0,16.0,F50199,48.271505,-3.814869,PLONEVEZ DU FAOU,,880
76,Brest,None,None,BANQUE DE TISSUS,0,Brest,1,0,0,16.0,F00013,48.406435,-4.497736,BANQUE DE TISSUS,,580
1466,None,None,PORT LOUIS,SALLE LOCMALO,0,PORT LOUIS,1,0,0,16.0,F38040,16.423578,-61.479707,PORT LOUIS-plasma,,1

(584, 16)

In [61]:
df_no_postcode.regionCode.value_counts()

regionCode
16.0    584
Name: count, dtype: int64

In [62]:
df.regionCode.value_counts()

regionCode
16.0    3234
19.0       9
23.0       5
Name: count, dtype: int64

In [85]:
df[(df.regionCode != 16.0) & (df.postCode == "")]

Empty DataFrame
Columns: [address1, address2, city, convocationLabel, distance, fullAddress, giveBlood, givePlasma, givePlatelet, regionCode, groupCode, latitude, longitude, name, postCode, samplingLocationCode]
Index: []

In [75]:
df_brit = df[df.regionCode == 16.0]
sample(df_brit, 3)

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode
1843,None,495 LA GREVE,LANVEOC,ESPACE NAUTIQUE,0,495 LA GREVE 29160 LANVEOC,1,0,0,16.0,F50124,48.292107,-4.452772,LANVEOC ESPACE NAUTIQUE 1,29160,5
2325,None,AVENUE ALPHONSE LEGAULT,BRUZ,ESPACE VAU GAILLARD,0,AVENUE ALPHONSE LEGAULT 35170 BRUZ,1,0,0,16.0,F70035,48.026524,-1.745072,2 BRUZ-GAILLARD DAM J+,35170,13
2256,None,AVENUE ABBE BARBEDET,ACIGNE,SALLE GLENMOR (avenue Abbé Barbedet),0,AVENUE ABBE BARBEDET 35690 ACIGNE,1,0,0,16.0,F70001,48.133980,-1.536855,2 ACIGNE-GLENMOR VE AM,35690,8

(3234, 16)

In [79]:
df_brit.loc["CP"] = df_brit.postCode.map(lambda x: x[:2] if x else x)

C:\Users\aurel\AppData\Local\Temp\ipykernel_29212\3244517452.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_brit.loc["CP"] = df_brit.postCode.map(lambda x: x[:2] if x else x)

In [86]:
df_brit[df_brit.CP == "44"]

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode,CP
2670,None,RUE DU PARC DES SPORTS,ST NICOLAS DE REDON,SALLE DU CHATEAU D'EAU,0.0,RUE DU PARC DES SPORTS 44460 ST NICOLAS DE REDON,1.0,0.0,0.0,16.0,F70187,47.643677,-2.061747,ST NICOLAS DE REDON MAT,44460,12,44
2671,None,RUE DU PARC DES SPORTS,ST NICOLAS DE REDON,SALLE DU CHATEAU D'EAU,0.0,RUE DU PARC DES SPORTS 44460 ST NICOLAS DE REDON,1.0,0.0,0.0,16.0,F70187,47.643677,-2.061747,ST NICOLAS DE REDON AM,44460,13,44

In [81]:
df_brit.CP.value_counts()

CP
35    844
56    837
29    681
      584
22    279
45      3
75      3
44      2
86      1
Name: count, dtype: int64

"22", "29", "35", "56"

45 = ORLEANS
75 = PARIS
44 = NANTES
86 = POITIERS

In [82]:
df_brit[df_brit.CP == "45"]

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode,CP
3225,ESPACE MULTI SERVICES - AGGLOMERATION MONTARGOIS,Rue de la Pontonnerie,MONTARGIS,Espace Multi Services,0.0,ESPACE MULTI SERVICES - AGGLOMERATION MONTARGO...,1.0,0.0,0.0,16.0,G45169,48.001575,2.722490,ZZZZZ,45200,2782,45
3230,Salle du Conseil,17 bis rue Aristide Briant,NOGENT SUR VERNISSON,Nogent sur Vernisson,0.0,Salle du Conseil 17 bis rue Aristide Briant 45...,1.0,0.0,0.0,16.0,G45173,47.845247,2.743089,Salle du Conseil,45290,2776,45
3231,Château,11 rue Pasteur,NOGENT SUR VERNISSON,NOGENT SUR VERNISSON,0.0,Château 11 rue Pasteur 45270 NOGENT SUR VERNISSON,1.0,0.0,0.0,16.0,G45173,49.276109,2.469000,Château,45270,3,45

In [88]:
df_no_brit = df[df.regionCode != 16.0]
df_no_brit

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode
337,COAT AN DOC'H,None,LANRODEC,ECOLE SECONDAIRE ET HORTICOLE,0,COAT AN DOC'H 22170 LANRODEC,1,0,0,NaN,F10505,48.532454,-3.033883,LYCEE COAT AN DOC'H,22170,1352
3224,None,16 - 18 rue Carnot,MONTARGIS,Salle Carnot,0,16 - 18 rue Carnot 45200 MONTARGIS,1,0,0,23.0,G45169,48.003376,2.738877,Salle Carnot,45200,2
3226,None,16-18 rue Carnot,MONTARGIS,Salle Carnot,0,16-18 rue Carnot 45200 MONTARGIS,1,0,0,23.0,G45169,48.003333,2.739207,ZZZZZ,45200,3
3227,None,5 rue du Puiseaux,MONTARGIS,Gymnase du Puiseaux,0,5 rue du Puiseaux 45200 MONTARGIS,1,0,0,23.0,G45169,47.993683,2.726787,Gymnase du Puiseaux,45200,4
3228,None,PLACE DU PATIS,MONTARGIS,MONTARGIS - SALLE DES FETES,0,PLACE DU PATIS 45200 MONTARGIS,1,0,0,23.0,G45169,47.999011,2.732873,SALLE DES FETES,45200,5
3229,None,4 avenue Georges Tribout,NOGENT SUR VERNISSON,Maison des Associations,0,4 avenue Georges Tribout 45270 NOGENT SUR VERN...,1,0,0,23.0,G45173,47.844353,2.737971,Maison des Associations,45270,2
3237,SALLES 336 R et 334 R AU RDC,14 AVENUE DUQUESNE,PARIS,MINISTERES SOCIAUX,0,SALLES 336 R et 334 R AU RDC 14 AVENUE DUQUESN...,1,0,0,19.0,I00014,48.852104,2.308965,SALLES 336 R et 334 R AU RDC,75007,4
3238,None,14 AVENUE DUQUESNE,PARIS,MINISTERES SOCIAUX-SALLES 304R ET 318,0,14 AVENUE DUQUESNE 75007 PARIS,1,0,0,19.0,I00014,48.852117,2.309103,SALLES 304R ET 318,75007,5
3239,SALLES 0304 R et 0334 R AU RDC,14 AVENUE DUQUESNE,PARIS,MINISTERES SOCIAUX,0,SALLES 0304 R et 0334 R AU RDC 14 AVENUE DUQUE...,1,0,0,19.0,I00014,48.851537,2.310623,SALLES 304 R et 334 R AU RDC,75007,58
3240,SALLE CORVETTO RDC,56 RUE DE LILLE,PARIS,CAISSE DES DEPOTS ET CONSIGNATIONS,0,SALLE CORVETTO RDC 56 RUE DE LILLE 75006 PARIS,1,0,0,19.0,I00048,48.859146,2.327979,SALLE CORVETTO RDC,75006,108
3242,None,56 RUE DE LILLE,PARIS,SALLE CORVETTO,0,56 RUE DE LILLE 75007 PARIS,1,0,0,19.0,I00048,48.859161,2.327975,SALLE CORVETTO,75007,3
3244,Véhicule de prélèvement sur le parking,au niveau de la porte de la Brosse (verte),COLLEGIEN,CENTRE COMMERCIAL BAY 2,0,Véhicule de prélèvement sur le parking au nive...,1,0,0,19.0,I05180,48.830251,2.673648,CAMION MATIN,77090,3
3245,Véhicule de prélèvement sur le parking,au niveau de la porte de la Brosse (verte),COLLEGIEN,Centre Commercial Bay 2,0,Véhicule de prélèvement sur le parking au nive...,1,0,0,19.0,I05180,48.830251,2.673648,CAMION AP.MIDI,77090,4
3246,CELLULE A CÔTE DE L'ENTREE DARTY,Rue du Général de Gaulle,COLLEGIEN,CENTRE COMMERCIAL BAY 2,0,CELLULE A CÔTE DE L'ENTREE DARTY Rue du Généra...,1,0,0,19.0,I05180,48.830251,2.673648,DANS LA GALERIE,77090,4927
3247,AUDITORIUM LAENNEC,149 RUE DE SEVRES,PARIS,HOPITAL NECKER,0,AUDITORIUM LAENNEC 149 RUE DE SEVRES 75015 PARIS,1,0,0,19.0,I07546,48.846481,2.315621,HOPTITAL NECKER,75015,1

In [91]:
df.postCode.str.len().value_counts()

postCode
5    2665
0     584
Name: count, dtype: int64

In [92]:
df[df.postCode == ""]

,address1,address2,city,convocationLabel,distance,fullAddress,giveBlood,givePlasma,givePlatelet,regionCode,groupCode,latitude,longitude,name,postCode,samplingLocationCode
0,Place de la Mairie,None,None,LARGITZEN,0,Place de la Mairie,1,0,0,16.0,BHA080,48.079732,7.357643,LARGITZEN,,MANS
1,Mairie,None,None,S.P. RETZWILLER,0,Mairie,1,0,0,16.0,BHA082,44.397060,0.805401,S.P. RETZWILLER,,MANS
2,Maison pour Tous,None,None,BISEL,0,Maison pour Tous,1,0,0,16.0,BHA101,14.814501,-61.110030,BISEL,,MANS
3,None,None,None,JETTINGEN,0,,1,0,0,16.0,BHA178,0.000000,0.000000,JETTINGEN,,MANS
4,None,None,None,GEISPITZEN,0,,1,0,0,16.0,BHA261,0.000000,0.000000,GEISPITZEN,,MANS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3223,None,None,None,PANELS,0,,1,0,0,16.0,FPANEL,0.000000,0.000000,PANELS,,575
3232,None,None,None,MDD de Châtellerault journée,0,,1,0,0,16.0,G86005,0.000000,0.000000,MDD de Châtellerault journée,,2
3234,Maison du Don,ZA du Sanital - 5 rue Jean Perrin,None,CHATELLERAULT - Maison du Don,0,Maison du Don ZA du Sanital - 5 rue Jean Perrin,1,0,0,16.0,G86005,50.359157,3.270767,MDD de Châtellerault matin,,3644
3236,PARIS7-MIN DUQUESNE,14 AVENUE DUQUESNE,PARIS,None,0,PARIS7-MIN DUQUESNE 14 AVENUE DUQUESNE PARIS,1,0,0,16.0,I00014,48.852117,2.309103,PARIS7-MIN DUQUESNE,,3
3243,None,None,None,None,0,,1,0,0,16.0,I05180,0.000000,0.000000,CENTRE COMMERCIAL BAY II (Col*,,2